---
title: "Mini-Project 2"
author: "Thao Phan & Asmita Gautam"
date: "March 24, 2017"
output: html_document
---

## Loading the data

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r, warning=FALSE, message=FALSE}
# FUNCTION 0: cand_ggPlot_func 
# plots candidate data  
cand_ggPlot_func <- function( data, title){
  ggplot( data, aes(x = cand_office_state, y = n, fill = cand_party_affiliation, width = .5)) +  
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  ggtitle(title) +
  scale_fill_manual(values = alpha(c("steelblue2", "indianred2"))) +
  labs( fill = "Candidate Party Affiliation" ) +
  labs(x = "Candidate's Office State") +
  labs(y = "# of Candidates in Each Party")
}
```


```{r}
# FUNCTION 1: "candidatesFunc"
# lets you compare candidate party affiliations for any two parties in any 11 eleven states in candidates data set
# s1, s2, s3, s4 etc. stands for the states 

candidatesFunc <- function( party1, party2, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10 ) {
  candidates %>%
    filter( cand_party_affiliation == c( party1, party2 ) ) %>%
    filter( cand_office_state == c( s1, s2, s3, s4, s5, s6, s7, s8, s9, s10 ) ) %>%
    group_by( cand_office_state, cand_party_affiliation ) %>%
    summarise( n = n() )
}
```


```{r, warning=FALSE, message=FALSE}
# Below we use the candidatesFunction

# Candidate Party affiliation in Top Ten Electoral Vote States
# States: CA, FL, GA, IL, MI, NC, NJ, NY, OH, PA, TX
top_10 <- candidatesFunc( party1 = "DEM", party2 = "REP", s1 = "CA", s2 = "FL", s3 = "GA", s4 = "IL", s5 = "MI", s6 = "NC", s7  = "NJ", s8 = "NY", s9 = "OH", s10 = "PA" )

#Background: We first used outside data to find the top 10 states with the most electoral votes because we thought that since they have the highest number of votes that they'd be a big influence on elections. We chose to focus on the Democratic and Republican parties because they're the most popular and most likely to win. We hypothesized that if a state is known to be more Democratic, then there'd be more Democrats running in that state than Republican candidates. 

# Analysis of ggplot: In our ggplot for the top 10 electoral vote states, we thought that since California and Pennsylvania is known to be more Democratic than Republican, that this would be seen in our data visualization. Our hypothesis turned out to be correct with both states having more Democratic candidates than Republicans. What's interesting is Illinois which we thought leaned more Republican than Democratic. It was interesting to see that there were much more Democratic candidates running than Republicans. This could be an error in our data set.

```


```{r}
cand_ggPlot_func( top_10, "Candidate Party Affiliation in Top Ten Electoral Vote States")
```

```{r, warning=FALSE, message=FALSE}
# Candidates in North Eastern States
# States: RI MA ME NH NJ NY PA CT VT 
north_cand <- candidatesFunc( party1 = "DEM", party2 = "REP", s1 = "RI", s2 = "MA", s3 = "ME", s4 = "NH", s5 = "NJ", s6 = "NY", s7  = "PA", s8 = "CT", s9 = "VT", s10 = NA )
```

```{r}
cand_ggPlot_func( north_cand, "Candidate Party Affiliation in North Eastern States")
```


```{r}
ggplot( north_cand, aes(x = cand_office_state, y = n, fill = cand_party_affiliation, width = .5)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  ggtitle("Candidate Party Affiliation in North Eastern States") +
  scale_fill_manual(values = alpha(c("steelblue2", "indianred2"))) +
  labs( fill = "Candidate Party Affiliation") +
  labs(x = "Candidate's Office State") +
  labs(y = " # of Candidates in Each Party")

```


```{r}
# FUNCTION 2: "committeesFunc"
# lets you compare any two parties in any 10 eleven states in committees data set
committeesFunc <- function( party1, party2, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10 ) {
  committees %>%
    filter( cmte_party_affiliation == c( party1, party2 ) ) %>%
    filter( cmte_state == c( s1, s2, s3, s4, s5, s6, s7, s8, s9, s10 ) ) %>%
    group_by( cmte_state, cmte_party_affiliation ) %>%
    summarise( n = n() )
}
```


```{r, warning=FALSE, message=FALSE}
# Committee Party affiliation in Top Ten Electoral Vote States
# States: CA, FL, GA, IL, MI, NC, NJ, NY, OH, PA
top_10_cmte <- committeesFunc( party1 = "DEM", party2 = "REP", s1 = "CA", s2 = "FL", s3 = "GA", s4 = "IL", s5 = "MI", s6 = "NC", s7  = "NJ", s8 = "NY", s9 = "OH", s10 = "PA")
```

```{r}
ggplot( top_10_cmte, aes(x = cmte_state, y = n, fill = cmte_party_affiliation, width = .5) ) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  ggtitle("Committee Party Affiliation in Top Ten Electoral Vote States") +
  scale_fill_manual(values = alpha(c("steelblue2", "indianred2"))) +
  labs( fill = "Committee Party Affiliation") +
  labs(x = "Committee's State") +
  labs(y = "# of Committees in Each Party")

```


```{r, warning=FALSE, message=FALSE}
# Committees Party Affiliation in Northeastern States
# States: AZ, CA, CO, ID, MO, NM, NV, OR, UT, WA, WY
north_com <- committeesFunc( party1 = "DEM", party2 = "REP", s1 = "CT", s2 = "MA", s3 = "ME", s4 = "NH", s5 = "NJ", s6 = "NY", s7  = "PA", s8 = "RI", s9 = "VT", s10 = "0", s11 = "0"  )
```

```{r}
ggplot( north_com, aes(x = cmte_state, y = n, fill = cmte_party_affiliation, width = .5) ) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  ggtitle("Committee Party Affiliation in Northeastern States") +
  scale_fill_manual(values = alpha(c("steelblue2", "indianred2"))) +
  labs( fill = "Committee Party Affiliation") +
  labs(x = "Committee's State") +
  labs(y = "# of Committees in Each Party")
```


```{r, warning=FALSE, message=FALSE}

# BELOW IS ALL THE CODE WITHOUT THE FUNCTIONS

# NOTE: I changed the order of the states in the filter() so that they are in alphabetical order
# ABC ORDER: CA, FL, GA, IL, MI, NC, NJ, NY, OH, PA, TX
cand1 <- candidates %>%
  filter(cand_party_affiliation == c("DEM", "REP")) %>%
  filter(cand_office_state == c("CA", "FL", "GA", "IL", "MI", "NC", "NJ", "NY", "OH", "PA", "TX")) %>%
  group_by(cand_party_affiliation, cand_office_state) %>%
  summarise( n = n() )
```

```{r}
ggplot( cand1, aes(x = cand_office_state, y = n, fill = cand_party_affiliation, width = .5)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  ggtitle("Candidates in Top Ten Electoral Vote States") +
  scale_fill_manual(values = alpha(c("steelblue2", "indianred2"))) +
  labs( fill = "Candidate Party Affiliation") +
  labs(x = "Candidate's Office State") +
  labs(y = " # of Candidates in Each Party")

```

```{r, warning=FALSE, message=FALSE}
com1 <- committees %>%
  filter(cmte_party_affiliation == c("DEM", "REP")) %>%
  filter(cmte_state == c("CA", "FL", "GA", "IL", "MI", "NC", "NJ", "NY", "OH", "PA", "TX")) %>%
  group_by(cmte_party_affiliation, cmte_state) %>%
  summarise( n = n() )
```

```{r}
ggplot( com1, aes(x = cmte_state, y = n, fill = cmte_party_affiliation, width = .5)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  ggtitle("Committee Party Affiliation in Top Ten Electoral Vote States") +
  scale_fill_manual(values = alpha(c("steelblue2", "indianred2"))) +
  labs( fill = "Committee Party Affiliation") +
  labs(x = "Committee's State") +
  labs(y = " # of Committees in Each Party")

```

```{r, warning=FALSE, message=FALSE}
party_affiliation <- house_elections %>%
  filter( party == c("D", "R") )%>%
  filter( state == c("CA", "FL", "GA", "IL", "MI", "NC", "NJ", "NY", "OH", "PA", "TX")) %>%
  group_by( party, state ) %>%
  summarise( n = n() )
```

```{r}
ggplot(party_affiliation, aes(x = state, y = n, fill = party, width = .5)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  ggtitle("Are there more Democrats or Republicans running for House Elections?") +
  scale_fill_manual(values = alpha(c("steelblue2", "indianred2"))) +
  labs( fill = "Political Party") +
  labs(x = "State & How Many Candidates Are in Each Party") +
  labs(y = " # Candidates in Each Party")


# In the chart below, we analyzed the political party affiliations of the 2011-2012 candidates (in the top ten electoral vote states) for the House of Representative. What we found was interesting. California, which leans more Democratic than Republican had more Republican candidates running for the House of Rep. Also, what we also found interesting was that several states (Florida, Ohio, N.Carolina, N.Jersey, and Pennsylvania) had just one party running for the house. We're not sure why this is, but we think that maybe it's because those states are primarily supportive of that particular party (whether Democrat or Republican) and this support is so strong that it probably makes candidates in the opposing party not run. This is just a hypothesis.  
```




```{r, warning=FALSE, message=FALSE}

# JOINED DATA

#rm(contributions, committees)
joined_data <- committees %>%
   inner_join(contributions, by = "cmte_id")
```


```{r, warning=FALSE, message=FALSE}
# We wanted to see if the states with more committees in our "Committee Party Affiliation in Top Ten Electoral Vote States" graph also had more transactions and contributions. So we merged the two datasets so that we could only look at the contributions for committees in our Committee graph to keep the data consistent and parallel. 

contrib_data <- joined_data %>%
  filter( cmte_party_affiliation == c("DEM", "REP") )%>%
  filter( cmte_state == c("CA", "FL", "GA", "IL", "MI", "NC", "NJ", "NY", "OH", "PA", "TX")) %>%
  group_by( cmte_state, cmte_party_affiliation ) %>%
  summarise( n = sum(transaction_amt) )
contrib_data
```

```{r}
p <- ggplot(contrib_data, aes(x = cmte_state, y = n, fill = cmte_party_affiliation, width = .5)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  ggtitle("") +
  scale_fill_manual(values = alpha(c("steelblue2", "indianred2"))) +
  labs( fill = "Political Party") +
  labs(x = "") +
  labs(y = "")
require(scales)
p + scale_y_continuous(labels = comma)
```





